docs: add aa-alchemy docs
OMGWINNING/aa-sdk-staging pull request #21
Opened 2023-09-26 21:53 UTC by avasisht23

2023-09-26 21:53 UTC, avasisht23 commented
Current dependencies on/for this PR:
* main
  * **PR #20** <a href="https://app.graphite.dev/github/pr/OMGWINNING/aa-sdk-private/20" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #21** <a href="https://app.graphite.dev/github/pr/OMGWINNING/aa-sdk-private/21" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/OMGWINNING/aa-sdk-private/21?utm_source=stack-comment).

2023-09-27 04:11 UTC, moldy530 commented on site/packages/aa-alchemy/index.md
> +This package contains `AlchemyProvider`, an implementation of `SmartAccountProvider` class defined in `aa-core`. It also contains middleware for accessing the Alchemy Gas Manager, an [EIP-4337](https
Contains middleware for Alchemy Gas Manager and for doing Fee Estimates according to the expectations of the rundler

2023-09-27 04:11 UTC, moldy530 commented on site/packages/aa-alchemy/index.md
> +If you are already using the `@alchemy/aa-core` package, you can simply install this package and start using the accounts. If you are not using `@alchemy/aa-core`, you can install it and follow the i
might wanna update this because this is confusing since it talks about `accounts`

2023-09-27 04:16 UTC, moldy530 reviewed
looks like chat gpt or copy pasta led to some janky docs lol

2023-09-27 04:16 UTC, moldy530 commented on site/packages/aa-alchemy/provider/introduction.md
> +`AlchemyProvider` is an extension of the `SmartAccountProvider` implementation. It supports features such as owner transfers, [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) message signing, and
the bit about owner transfers, message signing, and batched tx's is weird. That's dependent on the actual account being used.

The point of using AlchemyProvider is:
1. The configuration params are specific for connecting to alchemy RPC
2. It is configured to do correct fee estimation as expected by the rundler
3. provides methods for using Alchemy Gas Manager

2023-09-27 04:16 UTC, moldy530 commented on site/packages/aa-alchemy/provider/introduction.md
> +2.  [`signTypedData`](/packages/aa-alchemy/provider/withAlchemyGasManager) -- supports typed data signatures from the smart contract account's owner address.
this doesn't make any sense lol

2023-09-27 04:16 UTC, moldy530 commented on site/packages/aa-alchemy/provider/introduction.md
> +:::
I think you can just have the code snippet for initializing a new AlchemyProvider here? one of Sahil's PRs actually updates the `/provider.ts` snippet to use AlchemyProvider so you can probably just use that snippet directly

2023-09-27 04:18 UTC, moldy530 commented on site/packages/aa-alchemy/utils/introduction.md
I think we can get away with not having this section, wdyt?

2023-09-27 04:18 UTC, moldy530 commented on site/.vitepress/config.ts
> +            link: "/utils",
if we do think we need an intro (probs not) this should match the name of that file. but I don't think we need this

2023-09-29 22:32 UTC, avasisht23 commented on site/packages/aa-alchemy/index.md
> +If you are already using the `@alchemy/aa-core` package, you can simply install this package and start using the accounts. If you are not using `@alchemy/aa-core`, you can install it and follow the i
pr was WIP at this time and had lots of copy pasta!

2023-09-29 22:33 UTC, avasisht23 commented on site/packages/aa-alchemy/provider/introduction.md
> +`AlchemyProvider` is an extension of the `SmartAccountProvider` implementation. It supports features such as owner transfers, [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) message signing, and
pr was WIP at this time and had lots of copy pasta!

2023-09-29 22:33 UTC, avasisht23 commented on site/packages/aa-alchemy/provider/introduction.md
> +2.  [`signTypedData`](/packages/aa-alchemy/provider/withAlchemyGasManager) -- supports typed data signatures from the smart contract account's owner address.
The configuration params are specific for connecting to alchemy RPC

2023-09-29 22:33 UTC, avasisht23 commented on site/packages/aa-alchemy/provider/introduction.md
> +:::
I don't see his so I made `/alchemy-provider.ts`

2023-09-29 22:34 UTC, avasisht23 commented on site/packages/aa-alchemy/utils/introduction.md
couldn't hurt re: user expectation to click on section header and see a blurb. already wrote it so 🤷

2023-09-29 22:58 UTC, moldy530 requested changes
Make sure to add the returns and params sections to docs where necessary (the middleware docs mainly I think)

2023-09-29 22:58 UTC, moldy530 commented on site/packages/aa-alchemy/middleware/withAlchemyGasManager.md
> +# WithAlchemyGasManager
Nit match the names of the files in all these (this doc and the others in the PR)

2023-09-29 22:58 UTC, moldy530 commented on site/snippets/alchemy-provider.ts
> +import { LightSmartContractAccount } from "@alchemy/aa-accounts";
This shouldn't be necessary, provider.ts uses alchemy provider (we want to use this in other places as the default)

2023-09-29 22:58 UTC, denniswon approved these changes

2023-09-29 22:58 UTC, moldy530 commented
Also order on returns and params should follow the other ones (returns first then params)

2023-09-29 22:59 UTC, avasisht23 commented on site/snippets/alchemy-provider.ts
> +import { LightSmartContractAccount } from "@alchemy/aa-accounts";
oh didn't realize we updated, sg!

2023-09-29 23:12 UTC, moldy530 commented on site/packages/aa-alchemy/index.md
> +## Getting started
Maybe also include the provider creation code snippet here

2023-09-29 23:34 UTC, moldy530 approved these changes

2023-09-29 23:39 UTC, merged