feat: wrapSigWith6492 function in BaseSmartContractAccount for eip 6492
OMGWINNING/aa-sdk-staging pull request #73
Opened 2023-10-04 23:54 UTC by denniswon

https://github.com/alchemyplatform/aa-sdk/issues/107

2023-10-05 05:09 UTC, avasisht23 requested changes
great first attempt! left some comments that will require changes based on stuff I had discuss with Moldy, so ptal and lmk if you have any questions!

[this](https://github.com/OMGWINNING/aa-sdk-staging/pull/73#discussion_r1346783755) is the most important comment out of all below. lmk what you think. cc: @moldy530

2023-10-05 05:09 UTC, avasisht23 commented on packages/accounts/src/light-account/account.ts
> +  override async wrapSigWith6492(signature: Hash): Promise<Hash> {
with suggestion below, don't need this method overridden.

2023-10-05 05:09 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +  }
don't need this on the object. just use the util method, as it seems you're doing anyways (based on imports and usage in LightAccount)

2023-10-05 05:09 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +    return this.wrapSigWith6492(signature);
note name change below

2023-10-05 05:09 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +  async wrapSigWith6492(_signature: Hash): Promise<Hash> {
in sum, this method should have something like:

[pseudo-code, h/t Moldy for showing this to me]
```
const initCode = this.getAccountInitCode()
const address = initCode.substring(2, 42)
const callData = initCode.substring(42)

wrapWith6492({
  factoryAddress: address,
  initCode: callData,
  ...
})
```

2023-10-05 17:59 UTC, denniswon commented on packages/core/src/account/base.ts
> +  async wrapSigWith6492(_signature: Hash): Promise<Hash> {
For Account init code, when you say "we expect" any implementation of this to be the concatenation of the account's factory address and the abi encoded function data of the account factory's createAccount method.

-> is it possible that this is not? any edge cases possible?

2023-10-05 18:03 UTC, denniswon commented on packages/core/src/account/base.ts
> +  async wrapSigWith6492(_signature: Hash): Promise<Hash> {
4. `getAccountInitCode` -- this should return the init code that will be used to create an account if one does not exist. **Usually** this is the concatenation of the account's factory address and the abi encoded function data of the account factory's `createAccount` method.

2023-10-05 18:03 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +  async wrapSigWith6492(_signature: Hash): Promise<Hash> {
Good q. According to the 4337 spec: "The initCode field (if non-zero length) is parsed as a 20-byte address, followed by “calldata” to pass to this address. This method call is expected to create a wallet and return its address."

So we shouldn't expect any edge cases in behavior if the SCA and factory are spec-compliant.

Spec: https://eips.ethereum.org/EIPS/eip-4337#first-time-account-creation

2023-10-05 18:31 UTC, denniswon commented on packages/core/src/account/base.ts
> +  }
I put it in base so that 6492 is optional to implement/support?

2023-10-06 00:27 UTC, avasisht23 approved these changes
looks great, thanks Dennis. last few comments and then can ship.

btw, just to check, I ran the e2e tests [here](https://github.com/OMGWINNING/aa-sdk-staging/actions/runs/6425249659/job/17447586498) and the test for signwith6492 passed (ignore the sendUO ones failing that's due to network fee levels). In the future, would love for you to do this as part of showing a test plan for sdk changes!

2023-10-06 00:27 UTC, avasisht23 commented on packages/accounts/src/kernel-zerodev/account.ts
> +  signMessage(msg: Uint8Array | string): Promise<Hex> {
any reason we needed to move any of these methods around (maybe for the region)? doesn't look like you changed the functionality?

2023-10-06 00:27 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +   * @param _msg -- the message to sign
```suggestion
   * @param msg -- the message to sign
```

2023-10-06 00:27 UTC, avasisht23 commented on packages/core/src/account/base.ts
> +    ]);
```suggestion
    ]);

```

2023-10-06 05:37 UTC, denniswon commented
> looks great, thanks Dennis. last few comments and then can ship.
> 
> btw, just to check, I ran the e2e tests [here](https://github.com/OMGWINNING/aa-sdk-staging/actions/runs/6425249659/job/17447586498) and the test for signwith6492 passed (ignore the sendUO ones failing that's due to network fee levels). In the future, would love for you to do this as part of showing a test plan for sdk changes!

@avasisht23 yeah definitely. However, the e2e tests seem flaky. For me they never passed, even on main. 

```
        FAIL  |core| e2e-tests/simple-account.test.ts > Simple Account Tests > should execute successfully
       InvalidInputRpcError: Missing or invalid parameters.
       Double check you have provided the correct parameters.

       URL: https://polygon-mumbai.g.alchemy.com/v2/Uso1xa81jg0aNfevLwX2rEGz7AdObV0j
       Request body: {"method":"eth_sendUserOperation","params":[{"initCode":"0x","sender":"0xb856DBD4fA1A79a46D426f537455e7d3E79ab7c4","nonce":"0x620","callData":"0xb61d27f6000000000000000000000000b856dbd4fa1a79a46d426f537455e7d3e79ab7c4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000","signature":"0x9dbe0a2eb2ab0fb3c9751fb3680cea0640de3881a0e52caf678bb06788605dbe55d5c020ed668253cf5e10b683c84ec90ca2142ebbcf62629a097d6758c4409c1c","paymasterAndData":"0x","maxFeePerGas":"0x928717a7","maxPriorityFeePerGas":"0x92871794","callGasLimit":"0x238c","verificationGasLimit":"0xfce4","preVerificationGas":"0xab9c"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"]}

       Details: precheck failed: multiple violations: maxFeePerGas is 2458326951 but must be at least 18280746300, which is based on the current block base fee; maxPriorityFeePerGas is 2458326932 but must be at least 18280746284;
       Version: viem@1.10.8
        ❯ withRetry.delay.count.count ../../node_modules/viem/src/utils/buildRequest.ts:92:21
        ❯ attemptRetry ../../node_modules/viem/src/utils/promise/withRetry.ts:34:22

       ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
       Serialized Error: {
         "code": -32000,
         "details": "precheck failed: multiple violations: maxFeePerGas is 2458326951 but must be at least 18280746300, which is based on the current block base fee; maxPriorityFeePerGas is 2458326932 but must be at least 18280746284; ",
         "docsPath": undefined,
         "metaMessages": [
           "URL: https://polygon-mumbai.g.alchemy.com/v2/Uso1xa81jg0aNfevLwX2rEGz7AdObV0j",
           "Request body: {"method":"eth_sendUserOperation","params":[{"initCode":"0x","sender":"0xb856DBD4fA1A79a46D426f537455e7d3E79ab7c4","nonce":"0x620","callData":"0xb61d27f6000000000000000000000000b856dbd4fa1a79a46d426f537455e7d3e79ab7c4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000","signature":"0x9dbe0a2eb2ab0fb3c9751fb3680cea0640de3881a0e52caf678bb06788605dbe55d5c020ed668253cf5e10b683c84ec90ca2142ebbcf62629a097d6758c4409c1c","paymasterAndData":"0x","maxFeePerGas":"0x928717a7","maxPriorityFeePerGas":"0x92871794","callGasLimit":"0x238c","verificationGasLimit":"0xfce4","preVerificationGas":"0xab9c"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"]}",
         ],
         "shortMessage": "Missing or invalid parameters.
       Double check you have provided the correct parameters.",
         "version": "viem@1.10.8",
         "walk": "Function<walk>",
       }
       Caused by: RpcRequestError: RPC Request failed.

       URL: https://polygon-mumbai.g.alchemy.com/v2/Uso1xa81jg0aNfevLwX2rEGz7AdObV0j
       Request body: {"method":"eth_sendUserOperation","params":[{"initCode":"0x","sender":"0xb856DBD4fA1A79a46D426f537455e7d3E79ab7c4","nonce":"0x620","callData":"0xb61d27f6000000000000000000000000b856dbd4fa1a79a46d426f537455e7d3e79ab7c4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000","signature":"0x9dbe0a2eb2ab0fb3c9751fb3680cea0640de3881a0e52caf678bb06788605dbe55d5c020ed668253cf5e10b683c84ec90ca2142ebbcf62629a097d6758c4409c1c","paymasterAndData":"0x","maxFeePerGas":"0x928717a7","maxPriorityFeePerGas":"0x92871794","callGasLimit":"0x238c","verificationGasLimit":"0xfce4","preVerificationGas":"0xab9c"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"]}

       Details: precheck failed: multiple violations: maxFeePerGas is 2458326951 but must be at least 18280746300, which is based on the current block base fee; maxPriorityFeePerGas is 2458326932 but must be at least 18280746284;
       Version: viem@1.10.8
        ❯ request ../../node_modules/viem/src/clients/transports/http.ts:99:19
        ❯ withRetry.delay.count.count ../../node_modules/viem/src/utils/buildRequest.ts:69:18
        ❯ attemptRetry ../../node_modules/viem/src/utils/promise/withRetry.ts:34:22

       ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
       Serialized Error: {
         "code": -32000,
         "details": "precheck failed: multiple violations: maxFeePerGas is 2458326951 but must be at least 18280746300, which is based on the current block base fee; maxPriorityFeePerGas is 2458326932 but must be at least 18280746284; ",
         "docsPath": undefined,
         "metaMessages": [
           "URL: https://polygon-mumbai.g.alchemy.com/v2/Uso1xa81jg0aNfevLwX2rEGz7AdObV0j",
           "Request body: {"method":"eth_sendUserOperation","params":[{"initCode":"0x","sender":"0xb856DBD4fA1A79a46D426f537455e7d3E79ab7c4","nonce":"0x620","callData":"0xb61d27f6000000000000000000000000b856dbd4fa1a79a46d426f537455e7d3e79ab7c4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000","signature":"0x9dbe0a2eb2ab0fb3c9751fb3680cea0640de3881a0e52caf678bb06788605dbe55d5c020ed668253cf5e10b683c84ec90ca2142ebbcf62629a097d6758c4409c1c","paymasterAndData":"0x","maxFeePerGas":"0x928717a7","maxPriorityFeePerGas":"0x92871794","callGasLimit":"0x238c","verificationGasLimit":"0xfce4","preVerificationGas":"0xab9c"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"]}",
         ],
         "shortMessage": "RPC Request failed.",
         "version": "viem@1.10.8",
         "walk": "Function<walk>",
       }
       ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

        Test Files  1 failed (1)
             Tests  1 failed | 3 passed (4)
          Start at  22:26:29
          Duration  4.07s (transform 125ms, setup 24ms, collect 308ms, tests 3.57s, environment 0ms, prepare 48ms)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


 ——————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target test:run-e2e for 4 projects (5s)

2023-10-06 06:08 UTC, denniswon commented
replaced by PR https://github.com/OMGWINNING/aa-sdk-staging/pull/79 due to some unknown github error. same branch, but different PR?

2023-10-06 06:08 UTC, closed without merging