docs: aa-core withPaymasterMiddleware
OMGWINNING/aa-sdk-staging pull request #77
Opened 2023-10-06 04:46 UTC by avarobinson

docs: add aa-core withPaymasterMiddleware

2023-10-06 06:16 UTC, denniswon requested changes

2023-10-06 06:16 UTC, denniswon commented on site/packages/aa-core/provider/withPaymasterMiddleware
> +      content: withPaymasterMiddleware
```suggestion
      content: ISmartAccountProvider • withPaymasterMiddleware
```

2023-10-06 06:16 UTC, denniswon commented on site/packages/aa-core/provider/withPaymasterMiddleware
> +These middleware are often used together. The dummy paymaster data is used in gas estimation before we actually have paymaster data. Because the paymaster data has an impact on the gas estimation, it
Would be nice to add links to more info/reference on Paymaster in our docs (not sure which section would make most sense)

2023-10-06 06:16 UTC, denniswon commented on site/packages/aa-core/provider/withPaymasterMiddleware
> +    PaymasterDataMiddlewareOverrideFunction
Can we include actual code examples for these override functions?

2023-10-06 13:19 UTC, SahilAujla commented
We will also need to mention `dummyPaymasterDataMiddleware` and `paymasterDataMiddleware` in the same page as those are the related readOnly field and we decided to mention them along with these here.

For example, see `feeDataGetter` for `withFeeDataGetter`: https://github.com/SahilAujla/aa-sdk-private/blob/withFeeDataGetter/site/packages/aa-core/provider/withFeeDataGetter.md#feedatagetter

2023-10-06 13:25 UTC, avasisht23 reviewed
can you make the example more detailed? thanks!

2023-10-06 13:25 UTC, avasisht23 commented on site/packages/aa-core/provider/withPaymasterMiddleware
> +    PaymasterDataMiddlewareOverrideFunction
+1

For instance, let's define `DummyPaymasterDataMiddlewareOverrideFunction` and `PaymasterDataMiddlewareOverrideFunction` and then after setting the middleware, maybe call buildUserOperation and show in a comment how resulting uo struct fields changed in the resulting uo struct after build due to this middleware override

2023-10-10 15:48 UTC, avarobinson commented on site/packages/aa-core/provider/withPaymasterMiddleware
> +These middleware are often used together. The dummy paymaster data is used in gas estimation before we actually have paymaster data. Because the paymaster data has an impact on the gas estimation, it
@denniswon Any ideas on what paymaster links would be useful here? Added a more detailed description

2023-10-10 17:53 UTC, avasisht23 commented on site/packages/aa-core/provider/withPaymasterMiddleware.md
> +});
this wasn't addressed, but was looking for an example:

```suggestion
// Integrate the dummy paymaster data middleware and paymaster data middleware middleware with the provider
provider.withPaymasterMiddleware({
  DummyPaymasterDataMiddlewareOverrideFunction,
  PaymasterDataMiddlewareOverrideFunction,
});

// Define the user operation data
const userOpData = {
	target: "0xTARGET_ADDRESS", // Replace with your actual target address
	data: "0xSOME_DATA", // Replace with your actual data
};

const resultingUO = await provider.buildUserOperation(userOpData);
console.log("Modified paymasterAndData:", resultingUO.paymasterAndData);
```

2023-10-10 17:57 UTC, avasisht23 commented on site/packages/aa-core/provider/withPaymasterMiddleware.md
> +It's recommend to use this middleware if you want more customization over the gas and fee estimation middleware, including setting non-default buffer values for the fee/gas estimation.
I would even upsell and link to the Alchemy Provider, as it provides a cleaner interface

2023-10-10 17:59 UTC, avasisht23 approved these changes
left comments for few changes, then can ship.

2023-10-10 18:40 UTC, avasisht23 commented
make sure to lint this file, failing build atm: https://github.com/OMGWINNING/aa-sdk-staging/actions/runs/6473119250/job/17575156022?pr=77

2023-10-10 18:48 UTC, moldy530 commented on site/packages/aa-core/provider/withPaymasterMiddleware.md
> +  };
this one should probably show that it can be hardcoded. It's similar to dummySignature where it's `paymasterAndData` that will be successfully parsed by the paymaster contract and accurately represents the gas cost

2023-10-10 18:56 UTC, avasisht23 commented on site/packages/aa-core/provider/withPaymasterMiddleware.md
> +  };
+1, think can just mention that in the comment

2023-10-11 01:00 UTC, merged