docs: aa-core withGasEstimator
OMGWINNING/aa-sdk-staging pull request #78
Opened 2023-10-06 05:00 UTC by avarobinson

docs: add aa-core withGasEstimator

2023-10-06 06:19 UTC, denniswon requested changes

2023-10-06 06:19 UTC, denniswon commented on site/packages/aa-core/provider/withGasEstimator.md
> +      content: withGasEstimator
```suggestion
      content: ISmartAccountProvider • withGasEstimator
```

2023-10-06 06:19 UTC, denniswon commented on site/packages/aa-core/provider/withGasEstimator.md
> +Override the gasEstimator middleware which is used for setting the gasLimit fields on the UserOperation prior to execution.
Include reference links. Better with more explanation how gas estimation works.

2023-10-06 06:19 UTC, denniswon commented on site/packages/aa-core/provider/withGasEstimator.md
> +}));
Can we have more practical example? Don't think people will be able to figure out how to set these override funcs

2023-10-06 13:15 UTC, SahilAujla commented
We will also need to mention `gasEstimator` in the same page as that's the related readOnly field and we decided to mention them along with these here.

For example, see `feeDataGetter` for `withFeeDataGetter`: https://github.com/SahilAujla/aa-sdk-private/blob/withFeeDataGetter/site/packages/aa-core/provider/withFeeDataGetter.md#feedatagetter

2023-10-06 13:26 UTC, avasisht23 reviewed
can you make the example more detailed? thanks!

2023-10-06 13:26 UTC, avasisht23 commented on site/packages/aa-core/provider/withGasEstimator.md
> +}));
+1

For instance, after setting the middleware, maybe call buildUserOperation and show in a comment how resulting uo struct fields (callGasLimit, pvg, vgl) changed in the resulting uo struct after build due to this middleware override

2023-10-06 13:26 UTC, avasisht23 commented on site/packages/aa-core/provider/withGasEstimator.md
> +The provider with the gasEstimator middleware override.
```suggestion
The provider with the `gasEstimator` middleware override.
```

2023-10-10 17:51 UTC, avasisht23 commented on site/packages/aa-core/provider/withGasEstimator.md
> +}));
this wasn't addressed, but was looking for:

```suggestion
provider.withGasEstimator(async () => ({
  callGasLimit: 0n,
  preVerificationGas: 0n,
  verificationGasLimit: 0n,
}));

// Define the user operation data
const userOpData = {
  target: "0xTARGET_ADDRESS", // Replace with your actual target address
  data: "0xSOME_DATA", // Replace with your actual data
};

const resultingUO = await provider.buildUserOperation(userOpData);
console.log("Modified callGasLimit:", resultingUO.callGasLimit);
console.log("Modified preVerificationGas:", resultingUO.verificationGasLimit);
console.log("Modified verificationGasLimit:", resultingUO.verificationGasLimit);
```

2023-10-10 17:59 UTC, avasisht23 approved these changes
can you add the example build UO to the usage section? then can ship

2023-10-10 18:02 UTC, avarobinson commented
> can you add the example build UO to the usage section? then can ship

@avasisht23 just updated the example and read only fields

2023-10-10 18:46 UTC, moldy530 approved these changes

2023-10-10 21:00 UTC, merged