feat: add simple account abstraction example
OMGWINNING/aa-sdk-staging pull request #86
Opened 2023-10-08 21:52 UTC by avasisht23

2023-10-08 21:52 UTC, avasisht23 commented
Current dependencies on/for this PR:
* main
  * **PR #86** <a href="https://app.graphite.dev/github/pr/OMGWINNING/aa-sdk-staging/86" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/OMGWINNING/aa-sdk-staging/86?utm_source=stack-comment).

2023-10-10 13:22 UTC, rthomare requested changes

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/hooks/useMagicSigner.ts
> +import { chain, magicApiKey } from "@/config/client";
this is cool

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +// import { getRpcUrl } from "@/config/rpc"; // todo(ajay): use server side
rm?

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +          policyId: NEXT_PUBLIC_ALCHEMY_GAS_MANAGER_POLICY_ID, // todo(ajay): use server side
what do you mean server side? FWIW I think just doing it as a local env var is fine.

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +      rpcUrl: NEXT_PUBLIC_ALCHEMY_RPC_URL!, // todo(ajay): getRpcUrl(chain.id),
Let's not ship an example that give people the wrong way to do this. We should also make sure for our own internal classes we don't show people to do it this way either.

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +      rpcUrl: NEXT_PUBLIC_ALCHEMY_RPC_URL!, // todo(ajay): getRpcUrl(chain.id),
Going to block on making sure we proxy through our backend

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/config/rpc.ts
> +export function getRpcUrl(chainId: number) {
This isn't used right? Can we remove this? Also we should just be sending through our own proxy. Also for this example I'm sure it's find to just use one chain.

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/config/client.ts
> +export const simpleAccountFactoryAddress =
Why not use the default light account here? Can we use that instead? I feel like we should be pushing people to use light account for everything and not simple account.

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/components/Hero.tsx
> +"use client";
Left some comments in slack about this but TL;DR
- Can we move the AccountKit Docs Upsell to below the title
- Can we give the user some indication of what is happening i.e. we are deploying the smart contract account, now claiming the token.
- Can we also show the smart account address and link it to etherscan?

2023-10-10 13:22 UTC, rthomare commented on examples/aa-simple-dapp/src/app/globals.css
> +@tailwind base;
Why tailwind over chakra?

2023-10-10 13:24 UTC, rthomare commented on examples/aa-simple-dapp/src/components/Hero.tsx
> +"use client";
Also let's not call it Alchemy Token please 😅

2023-10-10 15:22 UTC, avasisht23 commented on examples/aa-simple-dapp/src/config/rpc.ts
> +export function getRpcUrl(chainId: number) {
doesn't this return the proxy url `api/rpc`? I ripped this from our webapp which seemed to work fine there.

2023-10-10 22:07 UTC, avasisht23 commented on examples/aa-simple-dapp/src/config/client.ts
> +export const simpleAccountFactoryAddress =
using LA now

2023-10-10 22:33 UTC, avasisht23 commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +      rpcUrl: NEXT_PUBLIC_ALCHEMY_RPC_URL!, // todo(ajay): getRpcUrl(chain.id),
resolved

2023-10-10 22:33 UTC, avasisht23 commented on examples/aa-simple-dapp/src/config/rpc.ts
> +export function getRpcUrl(chainId: number) {
resolved

2023-10-10 22:35 UTC, avasisht23 commented on examples/aa-simple-dapp/src/components/Hero.tsx
> +"use client";
all resolved

2023-10-10 23:59 UTC, rthomare approved these changes
Am I crazy are we using LightAccount? Otherwise LGTM

2023-10-10 23:59 UTC, rthomare commented on examples/aa-simple-dapp/src/config/rpc.ts
> +export function getRpcUrl() {
nit I'd say we can literally just kill this file and just add a const for "/api/rpc/"

2023-10-11 00:00 UTC, rthomare commented on examples/aa-simple-dapp/src/config/client.ts
> +export const simpleAccountFactoryAddress =
Let's use the useDefaultLightAccountFactoryAddress() function at somepoint here.

2023-10-11 00:04 UTC, avasisht23 commented on examples/aa-simple-dapp/src/hooks/useAlchemyProvider.ts
> +          return new LightSmartContractAccount({
@rthomare we use LA here!

2023-10-11 00:24 UTC, merged